server:
  port: 8285

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagement?useSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

root:
  url: /api/v1/employee-management

secret:
  key: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918